alias ls='ls -F --color=auto --group-directories-first'
alias cp='cp -i'
alias mv='mv -i'
alias grep='grep --color=auto '
#alias sbcl='rlwrap -c -D 2 sbcl'
alias sbcl="rlwrap -pred -r -s 65536 -m -i -c -D 2 sbcl"
alias rm='rm -I'
alias vi='nvim'
alias enable_vbox='sudo modprobe vboxdrv vboxnetadp vboxnetflt vboxpci'
alias disable_vbox='sudo modprobe -r vboxdrv vboxnetadp vboxnetflt vboxpci'
alias speed_test='wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'
alias :q='exit'
alias :Q='exit'
alias reflector_script='sudo /etc/pacman.d/Reflector_script.sh'
alias sudo='sudo '
alias start_mpd='systemctl start mpd.service --user'
alias stop_mpd='systemctl stop mpd.service --user'
alias start_mpdas='systemctl start mpdas.service --user'
alias stop_mpdas='systemctl stop mpdas.service --user'
alias wifi_on='nmcli radio wifi on'
alias wifi_off='nmcli radio wifi off'
alias container_run='sudo systemd-nspawn -u packager -D ~/Builds/Container'
